### ISSUE TITLE
Scramble MEDEVAC / Air Support function using Twilio

### ISSUE THREAD

**Issue by AJCStriker** [1st-rapid-response-force/catalyst#30]
This system is something I only thought of recently but is very important in nature.

Specification:

People in relevant airframe billets ( CAS Pilots / Heli Pilots / Heli Medics and Gunners ) should be able to mark themselves as available for two hour long windows in the web platform by pressing an "On Station" button inside - likely positioned in My Squad.

This then sets them as being able to be contacted for MEDEVACs if needed. They will be able to play other games and do other things.

In the event that they are required, officers should have a dispatch MEDEVAC button inside their admin panel.

This would take the following actions in sequence. 
1. Poke and Message all of their teamspeak IDs
2. Text their phone number via Twilio
3. Phone their mobile via Twilio with a message saying they are needed on deployment server.

They should be directed to immediately report to the officer who issued the request.

**Comment by mrgwilliam** [comment]
On Call implemented months ago
