### ISSUE TITLE
Front page content needs to be done

### ISSUE THREAD

**Issue by mrgwilliam** [1st-rapid-response-force/catalyst#31]
- Front page content needs to be finished a lot of the content is currently placeholder values.

**Comment by AJCStriker** [comment]
Working on this today - 31AUG2015

**Comment by mrgwilliam** [comment]
Oges already handled it focus on training content

**Comment by AJCStriker** [comment]
Oges did all the frontpage HTML?

**Comment by mrgwilliam** [comment]
He wrote all of the content that had placeholder content, explore our mos
section. We could do with the FAQ section being written.

**Comment by AJCStriker** [comment]
I meant building the rest of the frontpage. It's two divs long, thats not a normal front page.

**Comment by mrgwilliam** [comment]
Ah got it, I have his content on my local build. I will push it this
afternoon.

**Comment by AJCStriker** [comment]
Sounds reasonable. I sent you and Oges my BCT. 

Send me feedback so I can write out the video script.

**Comment by mrgwilliam** [comment]
The docs is locked down to 1st RRF accounts on Google make sure to open it
up for Oges.
