### ISSUE TITLE
Split Training Programs into sections

### ISSUE THREAD

**Issue by AJCStriker** [1st-rapid-response-force/catalyst#33]
As it stands the mechanism for displaying training content is not usable for anything other than demo content.

It should be split into sections, where a section comprises a written passage and a video. These sections should be viewable together, instead of one large wall of text.

**Comment by mrgwilliam** [comment]
This would lead to complicate things further, why doesn't the current structure of docs and videos work. I mean your BTC doc is practically the samething, You would just copy and paste it. All tabs also support video functionality.

**Comment by AJCStriker** [comment]
You will observe that my training document is split into four sections.

As BCT is the simplest of the courses, it still came to four sections amounting to 2000 words. 

Reading that in a block format is not fun for anyone and does not encourage compartmentalised learning. It also makes it hard to associate the video with the section.

This is not a question of possibility, sure you could be lazy and copy paste it. It is a question of practicality for the reader. As it stands right now, noone will read this because of brain fatigue.

If that is the case for the BCT manual, I assure you noone will read the 5000 words on trajectory ballistics.
