### ISSUE TITLE
How the fuck does the school system work?

### ISSUE THREAD

**Issue by AJCStriker** [1st-rapid-response-force/catalyst#60]

**Comment by mrgwilliam** [comment]
Yeah, it was incomplete. Working on this issue right now

**Comment by mrgwilliam** [comment]
1. Create a school or use an existing school
2. On the Admin Panel there is a date option on the [School menu](https://1st-rrf.com/admin/schools)
3. Click on Time/Date and you will be able to create sessions for the class
4. Once the Time/Date form has been filled out you will be able to see your session on the list
5. People will be able to sign up now and you will conduct your class as normal ( or brief the instructor and date)
6. Once the system detects that you or another person has been set as an instructor, they will be able to see their classes under the [instructor panel ](https://1st-rrf.com/my-training/instructor)
7. Once the class is conducted, you or the instructor will fillout the Completion or Cancellation form and we would then deal with it on the backend

I am working on the last part now

**Comment by mrgwilliam** [comment]
Implemented a change to the school system, sections have been gutted to simply ask for a documentation url, now students will be linked directly to the docs.

**Comment by mrgwilliam** [comment]
Implemented fully
